export const MCSL_A_MEET_EVENTS = {
    events: [
    { n: 1, gender: "M", ages: [0, 12], distance: 100, stroke: 5, maxEntries: 3 },
    { n: 2, gender: "F", ages: [0, 12], distance: 100, stroke: 5, maxEntries: 3 },
    { n: 3, gender: "M", ages: [13, 14], distance: 100, stroke: 5, maxEntries: 3 },
    { n: 4, gender: "F", ages: [13, 14], distance: 100, stroke: 5, maxEntries: 3 },
    { n: 5, gender: "M", ages: [15, 18], distance: 100, stroke: 5, maxEntries: 3 },
    { n: 6, gender: "F", ages: [15, 18], distance: 100, stroke: 5, maxEntries: 3 },
    { n: 7, gender: "M", ages: [0, 8], distance: 25, stroke: 1, maxEntries: 6 },
    { n: 8, gender: "F", ages: [0, 8], distance: 25, stroke: 1, maxEntries: 6 },
    { n: 9, gender: "M", ages: [9, 10], distance: 50, stroke: 1, maxEntries: 6 },
    { n: 10, gender: "F", ages: [9, 10], distance: 50, stroke: 1, maxEntries: 6 },
    { n: 11, gender: "M", ages: [11, 12], distance: 50, stroke: 1, maxEntries: 6 },
    { n: 12, gender: "F", ages: [11, 12], distance: 50, stroke: 1, maxEntries: 6 },
    { n: 13, gender: "M", ages: [13, 14], distance: 50, stroke: 1, maxEntries: 6 },
    { n: 14, gender: "F", ages: [13, 14], distance: 50, stroke: 1, maxEntries: 6 },
    { n: 15, gender: "M", ages: [15, 18], distance: 100, stroke: 1, maxEntries: 6 },
    { n: 16, gender: "F", ages: [15, 18], distance: 100, stroke: 1, maxEntries: 6 },
    { n: 17, gender: "M", ages: [0, 8], distance: 25, stroke: 2, maxEntries: 3 },
    { n: 18, gender: "F", ages: [0, 8], distance: 25, stroke: 2, maxEntries: 3 },
    { n: 19, gender: "M", ages: [9, 10], distance: 25, stroke: 2, maxEntries: 3 },
    { n: 20, gender: "F", ages: [9, 10], distance: 25, stroke: 2, maxEntries: 3 },
    { n: 21, gender: "M", ages: [11, 12], distance: 50, stroke: 2, maxEntries: 3 },
    { n: 22, gender: "F", ages: [11, 12], distance: 50, stroke: 2, maxEntries: 3 },
    { n: 23, gender: "M", ages: [13, 14], distance: 50, stroke: 2, maxEntries: 3 },
    { n: 24, gender: "F", ages: [13, 14], distance: 50, stroke: 2, maxEntries: 3 },
    { n: 25, gender: "M", ages: [15, 18], distance: 100, stroke: 2, maxEntries: 3 },
    { n: 26, gender: "F", ages: [15, 18], distance: 100, stroke: 2, maxEntries: 3 },
    { n: 27, 
        gender: "M", 
        ages: [0, 109], 
        distance: 200,
        stroke: 7,
        legs: [
            { distance: 50, stroke: 2 },
            { distance: 50, stroke: 3 },
            { distance: 50, stroke: 4 },
            { distance: 50, stroke: 1 },
          ],
          swimmers: [
            {ages: [0, 109], gender:'M'},
            {ages: [0, 109], gender:'M'},
            {ages: [0, 109], gender:'M'},
            {ages: [0, 109], gender:'M'}
        ], 
         maxEntries: 2 },
    { n: 28, 
        gender: "F", 
        ages: [0, 109], 
        distance: 200, 
        stroke: 7,
        legs: [
            { distance: 50, stroke: 2 },
            { distance: 50, stroke: 3 },
            { distance: 50, stroke: 4 },
            { distance: 50, stroke: 1 },
          ],
          swimmers: [
            {ages: [0, 109], gender:'F'},
            {ages: [0, 109], gender:'F'},
            {ages: [0, 109], gender:'F'},
            {ages: [0, 109], gender:'F'}
        ], 
        maxEntries: 2
    },
    { n: 29, gender: "M", ages: [0, 8], distance: 25, stroke: 3, maxEntries: 3 },
    { n: 30, gender: "F", ages: [0, 8], distance: 25, stroke: 3, maxEntries: 3 },
    { n: 31, gender: "M", ages: [9, 10], distance: 25, stroke: 3, maxEntries: 3 },
    { n: 32, gender: "F", ages: [9, 10], distance: 25, stroke: 3, maxEntries: 3 },
    { n: 33, gender: "M", ages: [11, 12], distance: 50, stroke: 3, maxEntries: 3 },
    { n: 34, gender: "F", ages: [11, 12], distance: 50, stroke: 3, maxEntries: 3 },
    { n: 35, gender: "M", ages: [13, 14], distance: 50, stroke: 3, maxEntries: 3 },
    { n: 36, gender: "F", ages: [13, 14], distance: 50, stroke: 3, maxEntries: 3 },
    { n: 37, gender: "M", ages: [15, 18], distance: 100, stroke: 3, maxEntries: 3 },
    { n: 38, gender: "F", ages: [15, 18], distance: 100, stroke: 3, maxEntries: 3 },
    { n: 39, gender: "M", ages: [0, 8], distance: 25, stroke: 4, maxEntries: 3 },
    { n: 40, gender: "F", ages: [0, 8], distance: 25, stroke: 4, maxEntries: 3 },
    { n: 41, gender: "M", ages: [9, 10], distance: 25, stroke: 4, maxEntries: 3 },
    { n: 42, gender: "F", ages: [9, 10], distance: 25, stroke: 4, maxEntries: 3 },
    { n: 43, gender: "M", ages: [11, 12], distance: 50, stroke: 4, maxEntries: 3 },
    { n: 44, gender: "F", ages: [11, 12], distance: 50, stroke: 4, maxEntries: 3 },
    { n: 45, gender: "M", ages: [13, 14], distance: 50, stroke: 4, maxEntries: 3 },
    { n: 46, gender: "F", ages: [13, 14], distance: 50, stroke: 4, maxEntries: 3 },
    { n: 47, gender: "M", ages: [15, 18], distance: 50, stroke: 4, maxEntries: 3 },
    { n: 48, gender: "F", ages: [15, 18], distance: 50, stroke: 4, maxEntries: 3 },
    { n: 49, 
        gender: "M", 
        ages: [0, 14], 
        distance: 175, 
        stroke: 6,
        legs: [
            { distance: 50, stroke: 1 },
            { distance: 50, stroke: 1 },
            { distance: 50, stroke: 1 },
            { distance: 25, stroke: 1 },
          ],
          swimmers: [
            {ages:[9, 10], gender:'M'},
            {ages:[11, 12], gender:'M'},
            {ages:[13, 14], gender:'M'},
            {ages:[0, 8], gender:'M'}
        ], 
        maxEntries: 2
    },
    { n: 50, 
        gender: "F", 
        ages: [0, 14], 
        distance: 175, 
        stroke: 6,
        legs: [
            { distance: 50, stroke: 1 },
            { distance: 50, stroke: 1 },
            { distance: 50, stroke: 1 },
            { distance: 25, stroke: 1 },
          ],
          swimmers: [
            {ages:[9, 10], gender:'F'},
            {ages:[11, 12], gender:'F'},
            {ages:[13, 14], gender:'F'},
            {ages:[0, 8], gender:'F'}
        ], 
        maxEntries: 2
    }
] };